apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usual-louse-dotnet-basic-development
  namespace: rhtap-test-organization-jk
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/usual-louse-dotnet-basic/overlays/development
    repoURL: https://github.com/rhtap-test-organization-jk/usual-louse-dotnet-basic-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-test-organization-jk
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
